# Configuration for Alacritty, the GPU enhanced terminal emulator

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 60 }
opacity = 1.0
padding = { x = 5, y = 5 }
decorations = "Full"
startup_mode = "Windowed"

[window.class]
instance = "Alacritty"

[scrolling]
history = 10000

[font]
size = 11.0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

# Color schemes
[colors]
# Gruvbox Dark
primary = { background = "#282828", foreground = "#ebdbb2" }

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

# To switch to Dracula theme, comment out the above colors section and uncomment below:

# [colors]
# primary = { background = "#282a36", foreground = "#f8f8f2" }

# [colors.normal]
# black = "#000000"
# red = "#ff5555"
# green = "#50fa7b"
# yellow = "#f1fa8c"
# blue = "#bd93f9"
# magenta = "#ff79c6"
# cyan = "#8be9fd"
# white = "#bfbfbf"

# [colors.bright]
# black = "#4d4d4d"
# red = "#ff6e67"
# green = "#5af78e"
# yellow = "#f4f99d"
# blue = "#caa9fa"
# magenta = "#ff92d0"
# cyan = "#9aedfe"
# white = "#e6e6e6" 